import { Inter } from "next/font/google";
import Meta from "@components/Meta/Meta";

const inter = Inter({ subsets: ["latin"] });

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({ pageName, children }) {
  return (
    <div className="flex flex-col">
      <Meta pageName={pageName} />
      <main className={inter.className}>{children}</main>
    </div>
  );
}
